GET http://localhost:3000/

### get all books
GET http://localhost:3000/api/books

### get single book
GET http://localhost:3000/api/books/2

### delete book
DELETE http://localhost:3000/api/books/1


###

GET https://jsonplaceholder.typicode.com/users

### Creat book

POST http://localhost:3000/api/books
Content-Type: application/json

{
  "id": "1",
    "title": "Book 6",
    "author": "Author 6",
        "isPublished": false,
        "year": 2024
}